# Generated by Django 5.2 on 2025-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
