# Generated by Django 5.2 on 2025-04-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightentry',
            options={'verbose_name_plural': 'Weight Entries'},
        ),
    ]
