# Generated by Django 5.2 on 2025-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_weightentry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
