# Generated by Django 5.2 on 2025-04-13 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_weightentry_timestamp_alter_weightentry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 19, 16, 20, 491451, tzinfo=datetime.timezone.utc)),
        ),
    ]
